sequencesPath = r"/user/cupyDTW/data/sequences" #r"../data/sequences"
targetpath    = r"/user/cupyDTW/data/target" #r"../data/target"
resultspath   = r"/user/cupyDTW/results"
configpath    = r"./config/"
dtwcudaname   = r"SHFL_FULLDTW_ALL.cuh"
dtwcudapath   = r"./cuDTW/include/kernels"
maincudaname  = r"main.cu"
maincudapath  = r"./cuDTW"
